# Generated by Django 4.2 on 2023-05-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplevocab', '0004_alter_vocabentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabentry',
            name='definition_override',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vocabentry',
            name='etymology_override',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vocabentry',
            name='examples_override',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vocabentry',
            name='synonyms_override',
            field=models.CharField(default='', max_length=255),
        ),
    ]
