# Generated by Django 4.2 on 2023-05-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplevocab', '0006_alter_vocabentry_definition_override_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabentry',
            name='definition_override',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vocabentry',
            name='etymology_override',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vocabentry',
            name='examples_override',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vocabentry',
            name='synonyms_override',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
