# Generated by Django 4.2 on 2023-05-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplevocab', '0007_alter_vocabentry_definition_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabentry',
            name='discovery_context',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
