# Generated by Django 4.2 on 2023-05-29 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplevocab', '0008_vocabentry_discovery_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresponse',
            name='word',
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='vocab_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simplevocab.vocabentry'),
        ),
    ]
