# Generated by Django 4.2 on 2023-06-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplevocab', '0009_remove_quizresponse_word_quizresponse_vocab_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabentry',
            name='discovery_source',
            field=models.CharField(max_length=255),
        ),
    ]
