# Generated by Django 4.2 on 2023-07-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplevocab', '0010_alter_vocabentry_discovery_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabentry',
            name='last_quiz',
        ),
        migrations.AlterField(
            model_name='vocabentry',
            name='definition_override',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Your Definition'),
        ),
        migrations.AlterField(
            model_name='vocabentry',
            name='discovery_context',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Discovery Context'),
        ),
        migrations.AlterField(
            model_name='vocabentry',
            name='discovery_source',
            field=models.CharField(max_length=255, verbose_name='Discovery Source'),
        ),
        migrations.AlterField(
            model_name='vocabentry',
            name='etymology_override',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Your Etymology'),
        ),
        migrations.AlterField(
            model_name='vocabentry',
            name='examples_override',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Your Examples'),
        ),
        migrations.AlterField(
            model_name='vocabentry',
            name='synonyms_override',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Your Synonyms'),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
